### ISSUE TITLE
Plans to publish 4.0.1 release?

### ISSUE THREAD

**Issue by rpetit3** [B-UMMI/ReMatCh#25]
I would like to help getting this submitted to Bioconda. 

Would it be possible to have v4.0.1 published as a release?

**Comment by cimendes** [comment]
Hello! 

Thank you for the offer! A bioconda package is much nicer to install than a git repo. :) There are a few fixed that are coming out. Once they are integrated into the master I'll make a new release! I'll keep you posted on it!

**Comment by rpetit3** [comment]
Sounds great! No rush!

**Comment by cimendes** [comment]
Realse available here: https://github.com/B-UMMI/ReMatCh/releases/tag/4.1.0

Closing this issue now. :)
